nome = str(input('Digite seu nome completo: ')).strip()
n = nome.split()
print('Muito prazer em te conhecer!')
print('Seu primeiro nome é {}'.format(nome.split()[0]))
print('Seu último nome é {}'.format(nome[nome.rfind(' '):]))
print('O seu último nome é {}'.format(n[len(n)-1]))
